# Generated by Django 3.1.7 on 2021-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustMail', models.CharField(max_length=100)),
                ('trustAddress', models.CharField(max_length=300)),
                ('trustOrg', models.CharField(max_length=100)),
                ('trustPhonenumber', models.CharField(max_length=100)),
                ('trustFrontimage', models.ImageField(upload_to='cars')),
            ],
        ),
    ]
