# Generated by Django 3.1.7 on 2021-03-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatwedo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='frontImage')),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='trustFrontimage',
            field=models.ImageField(upload_to='frontImage'),
        ),
    ]
