# Generated by Django 3.2 on 2021-05-31 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_post', '0003_auto_20210304_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimage',
            name='data',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
