# Generated by Django 3.2 on 2021-05-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_post', '0004_addimage_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addimage',
            old_name='data',
            new_name='date',
        ),
    ]
